# JIRA AI Agent Configuration

jira:
  # List of JIRA projects to analyze
  projects:
    - "PROD"  # Product issues
    - "TECH"  # Technical issues
    - "SUP"   # Support issues
  
  # Issue types to consider
  issue_types:
    - "Bug"
    - "Task"
    - "Story"
    - "Support"
  
  # Statuses to include in historical analysis
  resolved_statuses:
    - "Done"
    - "Resolved"
    - "Closed"
  
  # Fields to fetch from JIRA
  fields:
    - "summary"
    - "description"
    - "status"
    - "resolution"
    - "created"
    - "updated"
    - "assignee"
    - "reporter"
    - "priority"
    - "labels"
    - "comment"

llm:
  # Model configuration
  model: "llama-3.1-70b-versatile"
  temperature: 0.7
  max_tokens: 2048
  
  # Query matching settings
  similarity_threshold: 0.7
  top_k_results: 5

analytics:
  # Metrics to track
  enabled: true
  metrics:
    - "resolution_time"
    - "ticket_volume"
    - "query_patterns"
    - "resolution_success_rate"
  
  # Time ranges for analytics
  time_ranges:
    - "7d"   # Last 7 days
    - "30d"  # Last 30 days
    - "90d"  # Last 90 days

agent:
  # Agent behavior settings
  auto_suggest: true
  attach_documents: true
  confidence_threshold: 0.8
  max_suggestions: 3
